# Generated by Django 6.0.2 on 2026-03-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_order_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
